### ISSUE TITLE
Attachment paperclip does not display after sending message with attachment

### ISSUE THREAD

**Issue by kevin-dyrland** [r-lib/gmailr#100]
Hello!

I have a minor issue. I can send an email just fine, but when I receive it I'd like it to look as close to the real thing as possible. That is, when I send an email with an attachment, I'd like the end user to see a little paperclip. Any thoughts?

```
filepath<-paste("somepath.xlsx")
reboot.email <- mime() %>%
               to(c("Name <me@gmail>")) %>%
               from("Name <me@gmail>") %>%
               subject("Email from R") %>%
               html_body("I fill this in or else attach_part text does not display") %>%
               attach_part("Generic body text that does display") %>%
               attach_file(filepath)
send_message(reboot.email)
```

I receive the email and the attachment, but no paperclip! Any thoughts if you have a spare moment would be welcomed!

**Comment by jimhester** [comment]
I think this is now fixed, it now uses a content disposition of attachment rather than inline, which is why you weren't seeing the paperclip before.

**Comment by kevin-dyrland** [comment]
Awesome, thanks so much!
