### ISSUE TITLE
unable to authenticate through json file

### ISSUE THREAD

**Issue by vikram-rawat** [r-lib/gmailr#102]
I am trying to schedule a task of downloading attachments from emails and uploading them to a website after a certain manipulation in data.

but I am not able to authenticate my gmail with a credential file.

I have the file.
when I run

`use_secret_file('D:/R_CODE/David_lal/client_secret_511687295850-3pegdu3n0t2f8iu826m3cl4n1nklb08f.apps.googleusercontent.com.json')`

it gives me no error at all. 

but when I try to run a code.

```
messages(search = 'Stock File Provision',
         label_ids = "INBOX",1)[[1]]$messages[[1]]$id %>% 
    message() %>% 
    save_attachments(path = 'D:/R_CODE/David_lal/data/temp/'
                    ,user_id = 'me')
```

it gives me this error

`Error in itr(...) : Unauthorized (HTTP 401).`

I have a valid credential file. Which I have created by following the mentioned step on your site.

Please help me out here.

**Comment by jimhester** [comment]
This should be fixed by https://github.com/r-lib/gmailr/pull/113
