### ISSUE TITLE
Sending an email to multiple people

### ISSUE THREAD

**Issue by jnolis** [r-lib/gmailr#104]
From my testing it appears that to cc an email to multiple people you need to pass a single string to the `cc` function where the email addresses are comma separated:

```r
cc("example_email1@rstudio.com","example_email2@rstudio.com)
```

If this is indeed the right way to do it then the documentation should be updated to reflect that.

**Comment by hadley** [comment]
I just hit this too — I think it's a bug.

(To be clear you need to do `cc("example_email1@rstudio.com,example_email2@rstudio.com)` but the interface suggests that you can supply multiple email addresses)

**Comment by dcaud** [comment]
The quotations mark placement looks odd, hadley

**Comment by jimhester** [comment]
This was fixed as part of https://github.com/r-lib/gmailr/commit/12a4a3e30ea452b12c492fcbdbbbb728ff2c88c8
