### ISSUE TITLE
Refactor default app setup

### ISSUE THREAD

**Issue by jennybc** [r-lib/gmailr#116]
Instead of defaulting to an env var for the two pieces of data, it's probably better to use the env var to hold a file path to the JSON that holds the app's data.

This feels like a nicer workflow for us, e.g., sharing an app for revdep emails, for managing multiple apps, and so on.

This is closer to how Application Default Credentials works, too. That's about credentials, but it seems logical to use a similar pattern.

Also makes it easier to get the app from a JSON file or a JSON string.

**Comment by jimhester** [comment]
This is now done
