### ISSUE TITLE
Draft not deleted  in Gmail UI after email sent through script

### ISSUE THREAD

**Issue by j450h1** [r-lib/gmailr#119]
```
test_email <-
  gm_mime() %>%
  gm_to("EMAIL I'M SENDING TO") %>%
  gm_from("MY GMAIL EMAIL") %>%
  gm_subject("this is just a gmailr test") %>%
  gm_text_body("Can you hear me now?")

# Verify it looks correct
gm_create_draft(test_email)

# If all is good with your draft, then you can send it
gm_send_message(test_email)
```
This code works and the email gets sent successfully. Is there a delay of when the draft itself gets deleted? I had to manually delete it in the Gmail UI.

**Comment by j450h1** [comment]
I resent same message and was able to reproduce the problem. Doesn't appear to be a delay, so what strategy do you recommend to delete the draft?

**Comment by jimhester** [comment]
I think this is just how the API works, sending a message via the API is different than clicking the 'send' button from a draft on the Website. This is actually creating a completely new email and then sending that. If you want to delete the draft you need to call `gm_delete_draft()`.
