### ISSUE TITLE
gm_body is sometimes blank/Email loses formatting

### ISSUE THREAD

**Issue by cstangor** [r-lib/gmailr#120]
Hello,

Sometimes the body on the emails I retrieve show as blank, even though there is clearly a body in the message as I view it on gmail.

Is there any way to maintain the formatting of the message body when it is retrieved?

Thanks for the great library.

**Comment by jimhester** [comment]
This likely has to do with how the email is formatted, likely they contain only an HTML body and no text body or similar issues. You will have to inspect the data returned in the object yourself to determine the cause unfortunately. If you can provide a way to reproduce the problematic emails I will re-open this issue.
