### ISSUE TITLE
Messages only inconsistently send

### ISSUE THREAD

**Issue by beib** [r-lib/gmailr#126]
When using gm_send_message(), the same email that was sent a few moments ago would not be sent. It appears that R is processing something in the background and nothing happens for a long time. When I waited out, I got the following error messages. It seems a little better with a single email, but when I loop through a few emails in batch, this always happens. Please help.
`Error in gmailr_POST(c("messages", "send"), user_id, class = "gmail_message",  : 
  Gmail API error: 408`

**Comment by beib** [comment]
Here is some debugging code. Looks like it's stuck at this following link. 
`debug: output <- .Call(R_curl_fetch_memory, enc2utf8(url), handle, nonblocking)
Browse[2]> enc2utf8(url)
[1] "https://www.googleapis.com/gmail/v1/users/me/messages/send?uploadType=multipart"`

**Comment by EricGoldsmith** [comment]
I have run into a similar issue, which I [errantly attributed to a `gargle` issue](https://github.com/r-lib/gargle/issues/117), due to the timing.

Since roughly Oct 24th, I have experienced intermittent email failures, with status 408 (request timeout) or 502 (bad gateway), from code that has sent mail flawlessly for months.

I've not been able to uncover any clues with local troubleshooting. Though, have used `gmailr`'s `gm_last_response()` function to capture response details for both success and failure cases (can post `RDS` files here if needed)- but have not been able to decipher anything helpful from them.

The Google API metrics for the Gmail API show my successful attempts, but show nothing for the failure cases.

To rule out anything in my environment, I had a co-worker run the code from a different computer and in a different country - same results.

All this, taken together, suggest an issue with the Gmail API infrastructure. But, I've not found anyone else complaining of these issues. 

@jimhester, any troubleshooting advice would be welcomed.

**Comment by beib** [comment]
A temporary fix is to limit the wait time of no response, and get R to automatically try up to a dozen of times. Usually it takes 0 - 8 attempts to complete each send. Not ideal, and hope to see a real fix.

**Comment by EricGoldsmith** [comment]
As a test, I modified the `gmailr_query()` function (in `gmailr.R`) to do retries with exponential backoff - code below. 

Doesn't seem to help. Once you get into *whatever* the failure mode is, you're stuck.

```
gmailr_query <- function(fun, location, user_id, class = NULL, ..., upload = FALSE) {
  path_fun <- if (upload) gmail_upload_path else gmail_path

  safe_fun <- purrr::safely(fun)

  timeoutSecs <- 30
  nRetries <- 7

  for (i in seq_len(nRetries)) {
    safe_response <- safe_fun(path_fun(user_id, location), gm_token(), timeout(timeoutSecs), ...)
    response <- safe_response$result

    if (!is.null(safe_response$error) || status_code(response) >= 300) {
      backoff <- stats::runif(n = 1, min = 0, max = 2 ^ i - 1)

      if (!is.null(safe_response$error)) {
        base::message(sprintf("%s on attemp %d", safe_response$error$message, i))
      } else {
        base::message(sprintf("HTTP error %s on attemp %d", status_code(response), i))
      }

      if (i < nRetries) {
        base::message(sprintf("Backing off %0.2f seconds, and retrying ...", backoff))
        Sys.sleep(backoff)
      }
    } else {
      break
    }
  }

  the$last_response <- response

  if (is.null(response))
    stop()

  result <- content(response, "parsed")

  if (!is.null(class) && !is.null(result)) {
    class(result) <- class
  }
  result
}
```

**Comment by beib** [comment]
I noticed that when it's stuck, refreshing and fetching emails would get it work again, so here is one way that worked for me. Something in gm_threads() _might_ be helping with unstuck.
`cat("emailing for ID:", ID, fill=TRUE)
        weekly_email <-
        gm_mime() %>%
        gm_to(emailaddress) %>%
        gm_from("ADDFROM") %>%
        gm_subject("ADDSUBJ") %>%
        gm_text_body("ADDTEXT") %>%
        gm_attach_file(pdffile)

        send_attempts[[as.character(i)]] <- 0L
        sent <- FALSE
        while(!isTRUE(sent) && send_attempts[[as.character(i)]] < 21) { ## attempt 21 times until give up for each ID
            junk <- tryCatch(
gm_threads(paste(sample(letters, sample(1:5, 1, TRUE), replace = TRUE), collapse = ""), num_results = sample(1:10, 1, TRUE)),
error = function(e) e)
            out <- tryCatch({setTimeLimit(10, 10); gm_send_message(weekly_email)}, error = function(e) e)
            if (inherits(out, "error")) {
                sent <- FALSE
            } else if (isTRUE(tryCatch(out$labelIds[[1]] == "SENT", error = function(e) FALSE))) {
                sent <- TRUE
            } else {
                sent <- "unknown"
            }
            send_attempts[[as.character(i)]] <- send_attempts[[as.character(i)]] + 1L
        }
        cat("completed for ID:", ID, " in ", send_attempts[[as.character(i)]], " attempts.", fill=TRUE)
    }`

**Comment by jimhester** [comment]
Sorry, I am not sure why this would happen, perhaps the oauth authentication token is timing out or something similar, or it is just due to network issues. I don't really see a way to fix it in gmailr unfortunately.

**Comment by nicocriscuolo** [comment]
I am encountering the same problem and I can confirm that when I remove the functions to attach a file, I can send the email.

Thanks for your help!
