### ISSUE TITLE
Link to quota information somewhere

### ISSUE THREAD

**Issue by maelle** [r-lib/gmailr#127]
I.e. for the text "Only very heavy usage of the Gmail API requires payment, so use of the API for most people should be free." add https://developers.google.com/gmail/api/v1/reference/quota?

**Comment by jimhester** [comment]
Good idea!

**Comment by jennybc** [comment]
I've retitled this to better reflect what I think needs to happen: in some yet-to-be-determined place, talk about quotas.

This is linked to recovering from rate limiting, slowing down requests, retries, etc.
