### ISSUE TITLE
Gmailr not working in docker container

### ISSUE THREAD

**Issue by meheszlev** [r-lib/gmailr#128]
I've created a simple rscript to send emails with the help of gmailR.
As a local R script works just fine, but when I create a docker container, it fails.

I have this error msg:
Error: lexical error: invalid char in json text.
                                       authjson/gmailauth.json
                     (right here) ------^

I use the same json here what I use at the local r script. I also added the auth token. So I don't understand what is the problem.

**Comment by jimhester** [comment]
I am not sure either unfortunately, perhaps there is a quoting issue in your json.
