### ISSUE TITLE
Problem instaling package

### ISSUE THREAD

**Issue by maticabgd** [r-lib/gmailr#131]
Hello,

when I am trying to install package I am receiving message
"dependencies 'gargle', 'lifecycle' are not available for package 'gmailr'".

Can you help me please?

Aleksandar

**Comment by jimhester** [comment]
You need these packages to install gmailr, perhaps you are using an older version of R, or the packages did not yet have binary versions available. You can try installing the separately, e.g. `install.packages(c("gargle", "lifecycle"))` before trying to install gmailr.

**Comment by maticabgd** [comment]
Thanks!
Matic Aleksandar
