### ISSUE TITLE
Schedule send feature in Gmailr?

### ISSUE THREAD

**Issue by aeburger** [r-lib/gmailr#132]
Hi there,

Would it be possible, or are there plans to get gmailr to work with the schedule send feature in gmail?
Currently, the platform we use for our research project only allows us to schedule and send emails up to 4 weeks in advance.  Our study is much longer than this, so it would be great if we could use gmailr to schedule emails further in advance.
Thank you!

**Comment by jimhester** [comment]
The [gmail API](https://developers.google.com/gmail/api/v1/reference) does not seem to support this particular feature either. I imagine it is something specific to the gmail website.

So no gmailr will not have this, sorry!
