### ISSUE TITLE
Error in gm_save_attachments.   has_class(x, "gmail_message") is not TRUE

### ISSUE THREAD

**Issue by HadyShaaban** [r-lib/gmailr#136]
Hello dears,
Hope you are doing great.
I'm trying downloading excel sheets from gmail emails using gmailr
here is the code i'm using
```
LatestClientmessage = messages("SalesReport")
Email = message(id = LatestClientmessage [[1]]$"messages"[[1]]$"id")$snippet
Sheet = gm_save_attachments(Email , path = "D:/salesautomation/File.xlsx")
```
and the error appeared is 
```
Error in gm_save_attachments(Email, path = "D:/salesautomation/File.xlsx") : 
  has_class(x, "gmail_message") is not TRUE
```
What i'm using is to get this email thread last id and get its excel file. main purpose is to read this excel file into R then store its data into a googlesheet. So if i can read the excel file even without downloading it , this will be better , If not then i need to download it locally and read it then post at google sheet. Could you please help me ?
Stay safe

**Comment by jimhester** [comment]
Remove `$snippet`
