### ISSUE TITLE
Unable to fully automate gmailR

### ISSUE THREAD

**Issue by jreid88** [r-lib/gmailr#138]
Hello,
First off, I am not a programmer, I am only working with R for work and am self-taught, so please forgive me if something I say doesn't make sense. I am trying to automatically send an email to a gmail account in Rstudio. I setup gmailR and it seems to be working fine. However, I would like to run this script automatically through the terminal. I followed the suggestions made [here](https://github.com/r-lib/gmailr/issues/124), but the program still stops to check authentication in the browser. Is there any way around this? I've attached my code for reference. For what it's worth, the app has not been verified by google yet, although I'm not sure if that matters. The first few lines that are commented out are not included in the run after the initial setup. Thanks in advance.
```
#Send an email with the Tubewriter ouput
# path <- (mypathto.json")
# gm_auth_configure(path = path)
# 
# gm_auth(path = path,
#       cache = gargle::gargle_oauth_cache(),
#       use_oob = TRUE, token = NULL)

# Send token script:
appname <- "gmailr"
email   <- "<destinationemail@gmail.com>"
scopes  <- "full"
path    <- "mypathto.json"
key     <- "mykeyishere"
secret  <- "mysecretishere"
app     <- httr::oauth_app(appname, key, secret)

gm_auth_configure(key = key,
                  secret = secret,
                  path = path,
                  app = app,
                  cache = TRUE)

gm_auth(email = email,
token = httr::config("C:\\Users\\username\\.R\\gargle\\gargle-oauth\\6a971f054a1aa1801ed2171f9890334c_destinationemail@gmail"))


today <- Sys.Date()
subject <- paste(username, today, sep=" ")

tubewriter.email <- gm_mime() %>%
  gm_to("destinationemail@gmail.com") %>%
  gm_from("sourceemail@somewhere.com") %>%
  gm_subject(subject) %>%
  gm_html_body("") %>%
  gm_attach_file(tubewriter.output)

gm_send_message(tubewriter.email)
```

**Comment by jennybc** [comment]
Pardon the quick drive-by response but I passed through looking at something else.

> # gm_auth_configure(path = path)
> # 
> # gm_auth(path = path

That's a brief excerpt from your original code.

It can't lead to a sensible situation.

`gm_auth_configure()`'s `path` argument must lead to a JSON file containing an OAuth client ID and secret downloaded from Google Cloud Platform Console.

`gm_auth()`'s `path` argument must lead to a JSON file describing a service account.

There's no way this can ever succeed. Are you trying to auth as a normal user via OAuth or via a service account? If it helps, I am guessing you mean to auth as a normal user, via OAuth, using an OAuth app that you've acquired.

I suspect you've got other problems before your unattended auth will work, but this is the first blocker.

**Comment by sdisav** [comment]
Does it ask you to authenticate in the browser if you replace gm_auth_configure and gm_auth in the send token script with the following:
```
gm_auth_configure(path = path)

gm_auth(email = email,
        path = NULL,
        scopes = scopes,
        cache = gargle::gargle_oauth_cache(),
        use_oob = TRUE, 
        token = NULL)
```

**Comment by Ni-Ar** [comment]
> Does it ask you to authenticate in the browser if you replace gm_auth_configure and gm_auth in the send token script with the following:
> 
> ```
> gm_auth_configure(path = path)
> 
> gm_auth(email = email,
>         path = NULL,
>         scopes = scopes,
>         cache = gargle::gargle_oauth_cache(),
>         use_oob = TRUE, 
>         token = NULL)
> ```

I just tried this and it does not open the web browser and prompts to confirm the authentication. Thanks!
