### ISSUE TITLE
not using `gargle::tidyverse_app`!?

### ISSUE THREAD

**Issue by randy3k** [r-lib/gmailr#139]
I notice that `gmailr` doesn't use `gargle::tidyverse_app` in default. Is it a security concern? Though I also notice that `gmailr` is listed as one of the permitted packages here: https://github.com/r-lib/gargle/blob/325b668ee74b08af0b31ae1ad98d015ab2585420/R/inside-the-house.R#L9

**Comment by jennybc** [comment]
It is essentially impossible to get an oauth app verified with Gmail scopes. So I think it is safe to say that gmailr will always be "bring your own (oauth) app". Probably when I wrote that "inside the house" code I still had faint hope we would succeed. But that was shut down quite definitively by Google (I managed the verification process of the tidyverse app).

**Comment by randy3k** [comment]
Thanks for the information. It makes sense though as gmail scopes are highly sensitive. I was just curious why the tidyverse app isn't available for gmail but google drive and sheets.

**Comment by jennybc** [comment]
Currently Google makes a very clear distinction about the sensitivity of the scopes needed for Drive or Sheets work versus Gmail. Which makes sense.
