### ISSUE TITLE
gm_auth_configure failing silently?

### ISSUE THREAD

**Issue by laurenmarietta** [r-lib/gmailr#140]
Working in an R markdown file through RStudio, I'm struggling to get `gmailr` setup to work.

I've set up a Gmail API multiple times now, once following the instructions at https://gmailr.r-lib.org/ and again following the (somewhat more detailed) instructions at https://github.com/jennybc/send-email-with-r#prep-work-related-to-gmail-and-the-gmailr-package. 

However, when I run: 
```
gm_auth_configure(path = "path/to/clientid_and_secret.json")
gm_auth()
```
I get no output from the `gm_auth_configure` command - which from googling I think is supposed to prompt the opening of a browser window? - and get the following error from `gm_auth`:

```
Error: Can't get Google credentials.
Are you running gmailr in a non-interactive session? Consider:
  * Call `gm_auth()` directly with all necessary specifics.
```

Clearly I am doing something incorrectly, but I am getting no information as to what that might be. I am suspicious that `gm_auth_configure` is not working at all, but I am getting no feedback as to how. Any advice?

**Comment by r0bis** [comment]
Hmm, have you tried `gm_auth(email = TRUE)` and are you sure that the `yoursecret.json` can be found from R? I did a pretty thorough job testing and getting this to work and described what worked for me [here](https://stackoverflow.com/questions/60507013/gmailr-without-selecting-a-pre-authorised-account-in-r/62651398#62651398)

Maybe sometimes error messages are a little cryptic or insufficient, but the above error for me meant that either the cache was not found or the token inside it was not corresponding to the json file

**Comment by Dulani** [comment]
Just hit this wall too!  The key detail is the first sentence: 
>Working in an R markdown file through RStudio

If I run `gm_auth()` or even `gargle::token_fetch` from a notebook chunk, I either get an error (for `gm_auth`) or NULL (for `token_fetch`).  If I run it directly in the console, it appears to work (thus far).  I'm not sure why running from an .Rmd (notebook) chunk changes the behavior... but it does.

**Comment by jennybc** [comment]
Here is documentation on getting any gargle-using package, which includes gmailr, to auth noninteractively, such as in an R Markdown file:

https://gargle.r-lib.org/articles/non-interactive-auth.html#sidebar-2-i-just-want-my--rmd-to-render

https://gargle.r-lib.org/articles/non-interactive-auth.html#arrange-for-an-oauth-user-token-to-be-re-discovered
