### ISSUE TITLE
gm_subject() special characters

### ISSUE THREAD

**Issue by andresxmv** [r-lib/gmailr#148]
hi! I hope they are well :) I have doubts why adding special characters in the subject of the mail causes it to be sent with another subject (thousands of letters: c)

`gm_subject("Recepción")`

Thanks!

**Comment by rtheodoro** [comment]
I have been looking how to fix it. But I didn't find the solution. Do you?

**Comment by andresxmv** [comment]
Nope :(

**Comment by rtheodoro** [comment]
by the way, the right function is `gm_subject()`

**Comment by jennybc** [comment]
I can't reproduce this, i.e. if I send a message with `gm_subject("Recepción")`, the received message appears normal, with the subject "Recepción".

If it's still a problem, please open a new issue with more information. Such as details about the email (while it's still on your computer) and your operating system, locale, etc.
