### ISSUE TITLE
message(format = c("full", "minimal", "raw")) is missing "metadata"

### ISSUE THREAD

**Issue by williamgunn** [r-lib/gmailr#15]
Hey, it would be great to be able to fetch only email metadata, but the metadata format type isn't included. Is there another way to fetch only metadata that I missed?

**Comment by kazuya030** [comment]
Hi, I added 'metadata' feature.
If you can afford, please try 'install_github('kazuya030/gmailr')'
https://github.com/kazuya030/gmailr/commit/d8ac8429b5eb5b5aa4a25f955de10ca7f13fd3e1

I have sent pull request, so it might be merged.

**Comment by jimhester** [comment]
Closed by https://github.com/r-lib/gmailr/pull/38
