### ISSUE TITLE
Unable to automate email sending process in R

### ISSUE THREAD

**Issue by Mr-Hadoop-Hotshot** [r-lib/gmailr#151]
Hey guys when I tried to automate email sending process in R using {gmailr} and {taskscheduleR}, I encounter below mentioned problem.

R sends email every 3 minutes when scheduler is scheduled to run every "MINUTE". Manually it works well.

For example my script log messages:

LOG REPORT MESSAGE AS FOLLOWS:
**11:14** - Script scheduled successfully -Email ID generated in R - **Email Received.**

**11:15** - Script scheduled successfully -Email ID generated in R - **Email NOT Received.**

**11:16** - Script scheduled successfully -Email ID generated in R - **Email NOT Received.**

**11:17** - Script scheduled successfully -Email ID generated in R - **Email Received**

Any idea guys?!?
Anything to do with quota allocated by google and Python quickstart toolkit was used to create "credentials.json".

Thanks is advance.

**Comment by jennybc** [comment]
I'm afraid I would need a lot more information to help debug this.
