### ISSUE TITLE
How to get a refresh_token?

### ISSUE THREAD

**Issue by maelle** [r-lib/gmailr#152]
My question might be related to #143 (i.e. maybe I chose the wrong setting somewhere?)

I have realized I can't use gmailr with `gm_auth(cache = FALSE)` because the token I get has no refresh token.

I have created my own app and use

```r
gm_auth_configure(
  key = "blablabla.apps.googleusercontent.com",
  secret = "sEcReT",
  path = ""
)
```

Everything works fine i.e. I can send emails, but only if I don't try using a cached token.

**Comment by maelle** [comment]
Note that if I run `gargle::token_fetch(scopes = "https://www.googleapis.com/auth/userinfo.email")`, I obtain a refresh token so I'm pretty sure something in my app settings is wrong.

**Comment by maelle** [comment]
I have tried removing access to the app after reading https://stackoverflow.com/questions/10827920/not-receiving-google-oauth-refresh-token, which didn't help.

**Comment by maelle** [comment]
I'm wondering whether it has to do with the publication status, maybe one needs a public production app.

**Comment by jennybc** [comment]
What type of app did you create? You want "Desktop" and that is VERY IMPORTANT.

<img width="809" alt="Screen Shot 2021-05-04 at 9 14 53 AM" src="https://user-images.githubusercontent.com/599454/117035517-4286f480-acb9-11eb-9cbf-7c56d8632297.png">

<img width="390" alt="Screen Shot 2021-05-04 at 9 15 48 AM" src="https://user-images.githubusercontent.com/599454/117035682-77934700-acb9-11eb-897f-f86d696ced1c.png">

**Comment by jennybc** [comment]
No, getting a refresh token should work just fine for you, i.e. this has nothing to do with the app being verified.

**Comment by maelle** [comment]
Aaah that must be it, I'll retry asap, thanks a ton!

**Comment by maelle** [comment]
Thank you @jennybc, that was the problem!
