### ISSUE TITLE
Error: 'cli_warn' is not an exported object from 'namespace:cli'

### ISSUE THREAD

**Issue by jonmichael-caldwell** [r-lib/gmailr#157]
Hello,

I have been successfully using gmailr in a shiny app hosted on shinyapps.io without issue for the past month or so but today it has starting throwing the following error and crashing out anytime I call gm_send_message(). Nothing has changed in my configuration, passwords, etc so I'm a bit confused as to how to approach this problem. The error occurs both locally and on the deployed server. I originally set this up following the Setup instructions in the readme with the cached .secret folder and the credentials.json uploaded along with the app files as per the "Using gmailr in deployed applications instructions". All of this was working swimmingly until just now.

debug output:
`gm_send_message(email)
debugging in: gm_send_message(email)
debug: {
    mail <- as.character(mail)
    stopifnot(nullable(is_string)(thread_id), is_string(user_id))
    type <- match.arg(type)
    gmailr_POST(c("messages", "send"), user_id, class = "gmail_message", 
        query = list(uploadType = type), body = jsonlite::toJSON(auto_unbox = TRUE, 
            null = "null", c(threadId = thread_id, list(raw = base64url_encode(mail)))), 
        add_headers(`Content-Type` = "application/json"))
}
Browse[2]> c
**Auto-refreshing stale OAuth token.
Error: 'cli_warn' is not an exported object from 'namespace:cli'`**
____________________________________________________________________________________________________________________________
Session Info:
- Session info --------------------------------------------------------------------
 setting  value                       
 version  R version 3.6.2 (2019-12-12)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       America            
 date     2021-07-31                  

- Packages ------------------------------------------------------------------------
 package     * version date       lib source        
 askpass       1.1     2019-01-13 [1] CRAN (R 3.6.2)
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.6.2)
 backports     1.2.1   2020-12-09 [1] CRAN (R 3.6.3)
 base64enc     0.1-3   2015-07-28 [1] CRAN (R 3.6.0)
 blockrand   * 1.5     2020-04-06 [1] CRAN (R 3.6.3)
 broom         0.7.8   2021-06-24 [1] CRAN (R 3.6.2)
 bslib         0.2.5.1 2021-05-18 [1] CRAN (R 3.6.2)
 cachem        1.0.4   2021-02-13 [1] CRAN (R 3.6.3)
 cellranger    1.1.0   2016-07-27 [1] CRAN (R 3.6.2)
 **cli           2.5.0   2021-04-26 [1] CRAN (R 3.6.3)**
 colorspace    1.4-1   2019-03-18 [1] CRAN (R 3.6.1)
 crayon        1.4.1   2021-02-08 [1] CRAN (R 3.6.3)
 curl          4.3     2019-12-02 [1] CRAN (R 3.6.2)
 DBI           1.1.1   2021-01-15 [1] CRAN (R 3.6.3)
 dbplyr        2.1.1   2021-04-06 [1] CRAN (R 3.6.3)
 digest        0.6.27  2020-10-24 [1] CRAN (R 3.6.3)
 dplyr       * 1.0.6   2021-05-05 [1] CRAN (R 3.6.3)
 ellipsis      0.3.2   2021-04-29 [1] CRAN (R 3.6.3)
 fansi         0.4.1   2020-01-08 [1] CRAN (R 3.6.3)
 fastmap       1.1.0   2021-01-25 [1] CRAN (R 3.6.3)
 forcats     * 0.5.1   2021-01-27 [1] CRAN (R 3.6.3)
 fs            1.5.0   2020-07-31 [1] CRAN (R 3.6.3)
 gargle        1.2.0   2021-07-02 [1] CRAN (R 3.6.2)
 generics      0.1.0   2020-10-31 [1] CRAN (R 3.6.3)
 ggplot2     * 3.3.5   2021-06-25 [1] CRAN (R 3.6.2)
 glue          1.4.2   2020-08-27 [1] CRAN (R 3.6.3)
 **gmailr      * 1.0.0   2019-08-23 [1] CRAN (R 3.6.3)**
 gtable        0.3.0   2019-03-25 [1] CRAN (R 3.6.2)
 haven         2.4.1   2021-04-23 [1] CRAN (R 3.6.3)
 hms           1.1.0   2021-05-17 [1] CRAN (R 3.6.2)
 htmltools     0.5.1.1 2021-01-22 [1] CRAN (R 3.6.3)
 httpuv        1.6.1   2021-05-07 [1] CRAN (R 3.6.3)
 httr          1.4.2   2020-07-20 [1] CRAN (R 3.6.3)
 jquerylib     0.1.4   2021-04-26 [1] CRAN (R 3.6.3)
 jsonlite      1.7.2   2020-12-09 [1] CRAN (R 3.6.3)
 later         1.2.0   2021-04-23 [1] CRAN (R 3.6.3)
 lifecycle     1.0.0   2021-02-15 [1] CRAN (R 3.6.3)
 lubridate     1.7.10  2021-02-26 [1] CRAN (R 3.6.3)
 magrittr      2.0.1   2020-11-17 [1] CRAN (R 3.6.3)
 mime          0.9     2020-02-04 [1] CRAN (R 3.6.2)
 modelr        0.1.8   2020-05-19 [1] CRAN (R 3.6.2)
 mongolite   * 2.3.1   2021-04-30 [1] CRAN (R 3.6.3)
 munsell       0.5.0   2018-06-12 [1] CRAN (R 3.6.2)
 openssl       1.4.4   2021-04-30 [1] CRAN (R 3.6.3)
 pillar        1.6.1   2021-05-16 [1] CRAN (R 3.6.2)
 pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 3.6.2)
 promises      1.2.0.1 2021-02-11 [1] CRAN (R 3.6.3)
 purrr       * 0.3.4   2020-04-17 [1] CRAN (R 3.6.3)
 R6            2.5.0   2020-10-28 [1] CRAN (R 3.6.3)
 Rcpp          1.0.5   2020-07-06 [1] CRAN (R 3.6.3)
 readr       * 1.4.0   2020-10-05 [1] CRAN (R 3.6.3)
 readxl        1.3.1   2019-03-13 [1] CRAN (R 3.6.2)
 rematch2      2.1.2   2020-05-01 [1] CRAN (R 3.6.3)
 reprex        2.0.0   2021-04-02 [1] CRAN (R 3.6.3)
 rlang         0.4.11  2021-04-30 [1] CRAN (R 3.6.3)
 rstudioapi    0.13    2020-11-12 [1] CRAN (R 3.6.3)
 rvest         1.0.0   2021-03-09 [1] CRAN (R 3.6.3)
 sass          0.4.0   2021-05-12 [1] CRAN (R 3.6.3)
 scales        1.1.1   2020-05-11 [1] CRAN (R 3.6.3)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.6.3)
 shiny       * 1.6.0   2021-01-25 [1] CRAN (R 3.6.3)
 shinyauthr  * 1.0.0   2021-07-20 [1] CRAN (R 3.6.2)
 shinyjs     * 2.0.0   2020-09-09 [1] CRAN (R 3.6.3)
 sodium      * 1.1     2017-03-30 [1] CRAN (R 3.6.3)
 stringi       1.4.6   2020-02-17 [1] CRAN (R 3.6.2)
 stringr     * 1.4.0   2019-02-10 [1] CRAN (R 3.6.2)
 tibble      * 3.1.1   2021-04-18 [1] CRAN (R 3.6.3)
 tidyr       * 1.1.3   2021-03-03 [1] CRAN (R 3.6.3)
 tidyselect    1.1.1   2021-04-30 [1] CRAN (R 3.6.3)
 tidyverse   * 1.3.1   2021-04-15 [1] CRAN (R 3.6.3)
 utf8          1.2.1   2021-03-12 [1] CRAN (R 3.6.3)
 vctrs         0.3.8   2021-04-29 [1] CRAN (R 3.6.3)
 withr         2.4.2   2021-04-18 [1] CRAN (R 3.6.3)
 xml2          1.3.2   2020-04-23 [1] CRAN (R 3.6.3)
 xtable        1.8-4   2019-04-21 [1] CRAN (R 3.6.3)

**Comment by jonmichael-caldwell** [comment]
Was able to resolve this issue after updating cli to the latest github version, interestingly error persisted with the latest CRAN version. Error was thrown initially after OAuth stale token refresh failed. Fixed this by manually refreshing the cached .secret folder with the interactive OAuth session.

**Comment by jingydz** [comment]
## Bug
> autoplot(out_pca,data=dat,colour='label',size=0.1,label=TRUE,label.size=3)
Error: 'cli_abort' is not an exported object from 'namespace:cli'

## Check
> installed.packages()["cli", "Version"]
[1] "2.5.0"
> library(cli)
>

## Update
> install.packages("cli")
Installing package into ‘/T01Data/zhangjj/R/x86_64-pc-linux-gnu-library/4.0’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/cli_3.6.1.tar.gz'
Content type 'application/x-gzip' length 567293 bytes (553 KB)
==================================================
downloaded 553 KB
...
progress.c:352:3: warning: implicit declaration of function ‘nanosleep’; did you mean ‘sleep’? [-Wimplicit-function-declaration]
   nanosleep(&ts, NULL);
   ^~~~~~~~~
   sleep
make: *** [progress.o] Error 1
ERROR: compilation failed for package ‘cli’
* removing ‘/T01Data/zhangjj/R/x86_64-pc-linux-gnu-library/4.0/cli’

The downloaded source packages are in
        ‘/tmp/RtmpmQXUfD/downloaded_packages’
Warning message:
In install.packages("cli") :
  installation of package ‘cli’ had non-zero exit status

## Question
How to update to the newest version?

**Comment by jennybc** [comment]
@jingydz I recommend you take this up in the cli repo, where perhaps someone will recognize this compilation error.
