### ISSUE TITLE
GmailR with new google oauth 2.0 

### ISSUE THREAD

**Issue by careercoachme** [r-lib/gmailr#169]
I use GmailR and googledrive to access files and send emails non-interactively on Amazon AWS. I got an email this week that Google is changing it's oauth process from Sep/Oct this year. Will GmailR and googledrive continue to work in the same way with this update?

**Comment by ThoDuyNguyen** [comment]
Is there any update for this?

**Comment by jennybc** [comment]
As long as you are up-to-date with the released version of gargle, yes I believe gmailr should be working as usual, despite the auth changes at Google (partial deprecation of the out-of-bound flow).
