### ISSUE TITLE
Getting Started Vignette Seems Outdated

### ISSUE THREAD

**Issue by kputschko** [r-lib/gmailr#172]
Hello!

I'm trying to set setup gmailr but the [Quickstart](https://gmailr.r-lib.org/articles/gmailr.html#quickstart) "External Setup" section is glossing over a lot of information.  

In the provided link for the [Python Quickstart](https://developers.google.com/gmail/api/quickstart/python), there are no buttons to `Enable the Gmail API`, and after some further floundering to setup the API, there are no dialog boxes giving me an option to `DOWNLOAD CLIENT CONFIGURATION`.    Following the documentation leads me down a rabbit hole of setting up OAuth consent screens, setting up a scope, test users, and verifying a domain.  

None of this is intuitive, and the process to get started is far from quick!

**Comment by arp3ggio** [comment]
@kputschko I successfully used the instructions detailed in https://github.com/r-lib/gmailr/issues/143. I think this issue can be closed.

**Comment by jennybc** [comment]
Yes, lots of the documentation is very outdated here, but I am waking this package up after a long slumber. And yes I think we can close this in favor of #143.
