### ISSUE TITLE
Are there any changes in gm_auth_configure() -> error:  attempt to apply non-function

### ISSUE THREAD

**Issue by r0bis** [r-lib/gmailr#194]
I was able to make this work in 2020. Admittedly things might have changed, but troubleshooting is really difficult when I cannot make sense of the error message:

`gm_auth_configure(path = "client_secret_xxxx.json") `

gives error `Error in .auth$set_client(client) : attempt to apply non-function`

Everything that I can see about usage of gm_auth_configure suggests that I should supply it with a json file

**Comment by jennybc** [comment]
What version of gargle do you have? This rings a bell as a bug that I fixed there. TL;DR update gargle to the current CRAN version and try again.

**Comment by r0bis** [comment]
Thanks very much, I updated from 1.4.0 to 1.5.2 and now it is not complaining at all, sitrep is finding a token in the cache. I will double check that it actually can send e-mails with attachments, but so far so good. Now gm_auth is complaining of out-of-band flow (things change over 2 years) but I will get to the bottom of it.

**Comment by jennybc** [comment]
Sounds good! Yeah the out-of-band flow has changed a lot and that's just way it is, I'm afraid, given changes on the Google side. Hopefully you'll work through that OK.

**Comment by r0bis** [comment]
Yes, thanks, the e-mail works with update. OOB is ok and your article explains it very well. Maybe a short TLDR might be useful at the beginning to reassure it is not that hard (I could draft one and submit to you). Another key element to know early would be the timeframe the token may remain operational without a manual intervention. I understand If the project is Testing that would be 1 week and if it is in Published mode that would be 6 months. Best wishes
