### ISSUE TITLE
Error with gm_auth_configure pulling from gargle package

### ISSUE THREAD

**Issue by Thomas-Hagan** [r-lib/gmailr#199]
Recently I have received this error when trying to run this function through terminal

Error: 'gargle_oauth_client_from_json' is not an exported object from 'namespace:gargle'

Admittedly it may be a dependency issue, but I have tried to fix this several times to no avail. Any help would be greatly appreciated.

**Comment by jennybc** [comment]
The first thing I'd do is make sure you have the most current release of gargle installed from CRAN.

**Comment by Thomas-Hagan** [comment]
Both gargle and gmailr are up to date.

**Comment by jennybc** [comment]
Can you show me exact code and output? Please include calls to `packageVersion("gargle")` and `packageVersion("gmailr")`.

All I can say is `gargle_oauth_client_from_json()` is exported from gargle v1.5.2.

``` r
packageVersion("gargle")
#> [1] '1.5.2'
library(gargle)
exists("gargle_oauth_client_from_json", where = "package:gargle")
#> [1] TRUE
```

<sup>Created on 2024-05-13 with [reprex v2.1.0.9000](https://reprex.tidyverse.org)</sup>

**Comment by Thomas-Hagan** [comment]
Hi Jenny,

Apologies, this has resolved, no cause for alarm
