### ISSUE TITLE
magrittr dependency

### ISSUE THREAD

**Issue by lawremi** [r-lib/gmailr#42]
Is it really necessary to depend on magrittr? The pipe syntax seems orthogonal to an API package like gmailr. Should not the user be expected to `library(magrittr)` when they want access to the alternative syntax? Since the pipe theoretically applies to any API, is every library going to import and export the `%>%` symbol? That does not seem sustainable.

**Comment by jimhester** [comment]
I think you are probably right in this case, I don't feel like it adds much to gmailr in practice either, I personally tend to construct the email with one call to `gmailr::mime()` myself. Also there may be a bug in the generated mail body (https://github.com/jimhester/gmailr/issues/34)
