### ISSUE TITLE
Peer certificate cannot be authenticated with given CA certificates

### ISSUE THREAD

**Issue by RockScience** [r-lib/gmailr#44]
I am trying this, but I get a curl error. Is it because I have setup app specific passwords on my google account?

``` r
> install_github("jimhester/gmailr")
> install.packages("httpuv")
> library("gmailr")
> messages(search = "label:myLabel", user_id = user_id, num_results = 2)
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Peer certificate cannot be authenticated with given CA certificates
```

and my setup information:

``` r
R version 3.2.2 (2015-08-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu precise (12.04.5 LTS)

> packageVersion("RCurl")
[1] '1.95.4.7'
> packageVersion("gmailr")
[1] '0.6.0'
```
## I have tried:

 to install libcurl4-openssl-dev and reinstall RCurl 

``` r
sudo apt-get install libcurl4-openssl-dev
R
install.packages("RCurl")
```

but in vain

**Comment by RockScience** [comment]
I have finally managed to get rid of this error by running first (don't ask me why it fixes it, I have found this on another forum)

```r
httr::set_config( config( ssl_verifypeer = 0L ) )
```

Should we include this in gmailr?

**Comment by tgwhite** [comment]
I had a similar problem with a different site and your fix worked as well. The issue is that the target site's SSL chain is screwed up somehow and httr rejects a connection accordingly. Your fix tells the system "don't worry about it."

**Comment by jimhester** [comment]
httr uses curl, not RCurl so you need to update the curl package. However the error you are getting looks to me like your CA certificates are either not being found appropriately or are outdated in your OS.

If updating curl does not fix the issue I would open an issue at https://github.com/jeroenooms/curl/issues/.

In either case I don't believe this is a gmailr issue.

**Comment by WilDoane** [comment]
@jimhester: an additional possibility that too many packages ignore: in enterprise and government environments, users often must use custom CA bundles provided by their IT. Having a well documented example in the package docs that shows how to successfully point to a custom certificate file would be beneficial.

**Comment by potholiday** [comment]
Mine was cause because of incorrect system date and time. If that's the case you just have to change your computer date and time to the real one.

**Comment by thisismydesign** [comment]
`httr::set_config( config( ssl_verifypeer = 0L ) )`

> don't ask me why it fixes it

Seems very much like you're disabling peer verification which would not be the right way to go.

**Comment by jimhester** [comment]
@WilDoane, I agree with you, having a well documented example would be great, however I do not know what the best practice for how to do this is, nor the local setup to reproduce and test the suggested fixes. 

I think a combination of `CURL_CA_BUNDLE` and `CURL_SSL_BACKEND` environment variables can be used to configure the proper bundles for your system in the curl package, but really I think the best place for this documentation in the curl package, not in gmailr.
