### ISSUE TITLE
get character encoding from content-type

### ISSUE THREAD

**Issue by lawremi** [r-lib/gmailr#47]
After decoding the message payload, gmailr could extract the `charset` from the `Content-Type` header. By default on the web, this is iso-8859-1, which R calls "latin1". That could be set on the string, e.g., 

```
Encoding(x) <- "latin1"
```

But then again, I'm not sure where that actually helps, since R always displays and writes strings in the current locale, so things get weird.

**Comment by jimhester** [comment]
I am definitely not an expert on how character encodings work in R, setting the encoding based on `Content-Type` seems to me like something httr should handle if it provides a benefit...

**Comment by lawremi** [comment]
Not sure what httr could do in this case, since you have to decode the base64 stuff first.
