### ISSUE TITLE
Send mail/Drafts

### ISSUE THREAD

**Issue by lcolladotor** [r-lib/gmailr#5]
Hi,

Unless I missed it, I couldn't find a way in `gmailr` to create new emails. From https://developers.google.com/gmail/api/v1/reference/users/drafts/create it seems to me that the Google API does support creating new drafts. I don't know how hard it would be, but if something like a `create_draft()` function was added, then together with `send_draft()` we could send emails from `gmailr`. That would then open up to the use case that @kbroman talked about in his [blog](http://kbroman.wordpress.com/2014/09/04/error-notifications-from-r/).

<blockquote class="twitter-tweet" lang="en"><p><a href="https://twitter.com/kwbroman">@kwbroman</a> you should also check out <a href="https://t.co/11t6IA4bfQ">https://t.co/11t6IA4bfQ</a></p>&mdash; Hadley Wickham (@hadleywickham) <a href="https://twitter.com/hadleywickham/status/507192305816567808">September 3, 2014</a></blockquote>

<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

Cheers,
Leo

**Comment by sanjmeh** [comment]
@jimhester  & @jennybc , this appears a really old post but I am still facing problems in send_draft() and attach_part() functions... and many more.  Seems either we have not moved on the package or CRAN is not updated. I have version 0.7.1 from CRAN.
