### ISSUE TITLE
loading gmailr library breaks View in RStudio

### ISSUE THREAD

**Issue by jamespmcguire** [r-lib/gmailr#53]
due to the body() function?

> df = data.frame(a = c(1,2,3), b = c(3,4,5))
> View(df)
> Error in View : no applicable method for 'body' applied to an object of class "function"
> Error in UseMethod("body") : 
>   no applicable method for 'body' applied to an object of class "function"
> traceback()
> 12: body(object)
> 11: .rs.resolveAliasedSymbol(object)
> 10: .rs.getAnywhere(name, src)
> 9: args(obj)
> 8: print(args(obj))
> 7: eval(expr, envir, enclos)
> 6: eval(expr, pf)
> 5: withVisible(eval(expr, pf))
> 4: evalVis(expr)
> 3: capture.output(print(args(obj)))
> 2: .rs.getSignature(.rs.getAnywhere(name, src))
> 1: (function (name, src) 
>    {
>        if (identical(src, "")) 
>            src <- NULL
>        result <- .rs.getSignature(.rs.getAnywhere(name, src))
>        result <- sub("function ", "", result)
>        .rs.scalar(result)
>    })("traceback", "package:base")

**Comment by jimhester** [comment]
The body function is now deprecated, this will be fixed once it is removed entirely.

**Comment by jennybc** [comment]
I've advanced the deprecation of un-prefixed functions like `body()` now, which will go into force in what is anticipated to be version 2.0.0. Specifically, we're going from `lifecycle::deprecate_soft()` to `lifecycle::deprecate_warn()`. My plan is to fully deprecate them (remove them!) after 2.0.0 has been out there for some short-but-respectable amount of time.

So there's nothing to do here but to continue on our path.
