### ISSUE TITLE
Body is blank after attaching file

### ISSUE THREAD

**Issue by Vestaxis** [r-lib/gmailr#60]
I haven't actually come across an example which does this but I was hoping that this would work: 
write.csv(file = "iris.csv", iris)

mime() %>%
  to('someaddress@somewhere.com') %>%
  from("someaddress@somewhere.com") %>%
  subject("Test subject") %>%
  text_body("Test body") %>%
  attach_file("iris.csv") %>%
  send_message()

Although the email is sent with the attachment, the body is not included in the email. It seems to be dropped entirely from the message when it's sent although the object that goes into send_message() still includes the body part. It doesn't work with html_body() either, attaching multiple files works fine. 

This email does include the body:

mime() %>%
  to('someaddress@somewhere.com') %>%
  from("someaddress@somewhere.com") %>%
  subject("Test subject") %>%
  text_body("Test body") %>%
  #attach_file("iris.csv") %>%
  send_message()

**Comment by puterleat** [comment]
I have this issue too... I also find that I can't send both text and html body parts.

**Comment by shihs** [comment]
I got the same problem...
Do you guys have any method to solve this problem?

**Comment by jrfarrer** [comment]
I have the same issue and haven't figured out a solution yet.

**Comment by jonspring** [comment]
I had some luck using the format below. For some reason taking out either the html_body or the attach_part terms would hide the text.

  html_msg <- mime() %>%
    to("emails@foo.com") %>%
    from("emails@bar.com") %>% 
    subject(email_subject) %>%
    html_body(body_text) %>% 
    attach_part(body_text) %>% 
    attach_file(attachment) -> file_attachment

**Comment by CarlBoneri** [comment]
It would seem like there are duplicated fields generated from the mime construction, so it's last-in first-out as far as the request is concerned... thus dropping any body info related to a message. @jonspring 's solution works nicely.

**Comment by nfrimando** [comment]
If the message was html, it would still appear as text though. Is there any way to send html along with an attachment?

**Comment by smithjd** [comment]
I'm trying to send ***2*** attachments.  Getting them both in the one email is more important than getting the body to show nicely (or at all).  Here is the only combination of calls that I could get to work:

```
test_email <- mime(
  To = gmail_to_list,
  From = my_address,
  Subject = paste("Weekly reports as of", today()),
  html_body = body_text ) %>%
  attach_file("past_meetings_report.html", type = "html") %>%
  attach_file("scheduled_meetings_report.html", type = "html")

send_message(test_email)
```
At some point I managed to send an HTML body and one attachment, but the HTML didn't render.  So this seems to be a very fragile interface.

**Comment by vedutkarsh** [comment]
> If the message was html, it would still appear as text though. Is there any way to send html along with an attachment?

@nfrimando 

There seems to be a nice workaroud to get the HTML outputs too. All you need to do is attach_file() the .html along with the attachment.

Following format works for me.

email <-
  mime() %>% from("email@foo.com") %>% to (emai@bar.com) %>%
  subject("Subject") %>% html_body("") %>%
  attach_file("/home/email.body.html") %>%
attach_file("main_file.xlsx" )

send_message(email)

Note:- Through trial and errors it appears that any arbitrary argument needs to be passed to the 'html_body()' without which this wouldn't work. Hence the empty quotes there.

**Comment by jimhester** [comment]
This is now fixed without workarounds

``` r
pkgload::load_all("~/p/gmailr")
#> Loading gmailr
write.csv(iris, "iris.csv")
gm_mime() %>%
  gm_from("email@foo.com") %>%
  gm_to("email@bar.com") %>%
  gm_subject("I bought you") %>%
  gm_text_body('Some flowers!') %>%
  gm_attach_file("iris.csv") %>%
  gm_create_draft()
#> Draft Id: r-2808894807153655050 
#> Thread Id: 16cab9f58efda151
```

<sup>Created on 2019-08-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

![Screen Shot 2019-08-19 at 4 44 24 PM](https://user-images.githubusercontent.com/205275/63298051-ad538a80-c2a0-11e9-9244-096780b58cbc.png)
