### ISSUE TITLE
How to read zip attachment that has cvs in it

### ISSUE THREAD

**Issue by maaraaj** [r-lib/gmailr#62]
I receive an email everyday with a fixed subject line that has a attachment in a zip format which contains a csv (.csv.gz format)
I have successfully set up this package and it's working fine. 
Can you please help me further. I want to read my csv in R.

Thanks in advance.

**Comment by talgalili** [comment]
You would probably need to download the file and unpack it, regardless of gmailr. I suggest you to look at stackoverflow.com on how to deal with the file.

**Comment by jimhester** [comment]
Retrieve the attachment with `gmailr::attachment()`, then read the file with `readr::read_csv()`, it will automatically extract the file for you.
