### ISSUE TITLE
Adding attachment obscures body of message.

### ISSUE THREAD

**Issue by mattbaggott** [r-lib/gmailr#69]
Message contents inserted with text_body() or html_body are no longer visible when attach_file() is also used to attach a pdf.  The issue seems to fixable by inserting an apparently missing boundary line before the text section.

**Comment by RobStilson** [comment]
I am experiencing this as well. Can you give some example code of "inserting an apparently missing boundary line before the text section"? Thank you.

**Comment by mattbaggott** [comment]
Here's a clunky fix in which I modified send_message():

`send_message_fixed <- function (mail, type = c("multipart", "media", "resumable"), 
                                thread_id = NULL, user_id = "me") {
  mail <- as.character(mail)
  # infer boundary line
  boundary_line <- paste0(stringr::str_replace(stringr::str_extract(mail,"boundary=.{1,}"),"boundary=","--"),"\r\n")
  # find where to insert it
  need_boundary_before_here <- stringr::str_locate_all(mail,"MIME")[[1]][2,1]
  # insert it
  mail <- paste0(substr(mail,1,need_boundary_before_here-1),
                 boundary_line,
                 substr(mail,need_boundary_before_here,stringr::str_length(mail)))
  mail <- stringr::str_replace(mail,"Content-Disposition: inline; filename=","Content-Disposition: attachment; filename=")
  stopifnot(gmailr:::nullable(gmailr:::is_string)(thread_id), gmailr:::is_string(user_id))
  type <- match.arg(type)
  gmailr:::gmailr_POST(c("messages", "send"), user_id, class = "gmail_message", 
                       query = list(uploadType = type), 
                       body = jsonlite::toJSON(auto_unbox = TRUE, 
                                               null = "null", c(threadId = thread_id, 
                                                                list(raw = gmailr:::base64url_encode(mail)))), 
                       httr::add_headers(`Content-Type` = "application/json"))
}`

**Comment by RobStilson** [comment]
Thank you! I needed to change the line
httr::add_headers(Content-Type = "application/json")) to 
httr::add_headers("Content-Type" = "application/json")) 
and then it worked perfectly!

**Comment by jimhester** [comment]
This is now fixed.
