### ISSUE TITLE
Smartquotes cause error in encoding as quoted printable

### ISSUE THREAD

**Issue by jimhester** [r-lib/gmailr#77]
```r
quoted_printable_encode("\u2018")
#> Error in vapply(x, function(xx) fun(xx), character(1)) :
#>  values must be length 1,
#> but FUN(X[[1]]) result is length 3
```

**Comment by zachmaurer** [comment]
For what it's worth, I also got a similar error when sending content that used the character "ç".

`quoted_printable_encode("ç")
# Error in vapply(x, function(xx) fun(xx), character(1)) : 
#  values must be length 1,
# but FUN(X[[1]]) result is length 2`

Just wanted to say, I love gmailr -- a really great package. Thank you so much!

**Comment by jimhester** [comment]
One easy way to convert these characters is is convert them to ascii equivalents with `stringi::stri_trans_general(x, "Latin-ASCII")`
