### ISSUE TITLE
as.character.mime(body, newline = "\n")

### ISSUE THREAD

**Issue by rpietro** [r-lib/gmailr#84]
Jim, awesome package. I am trying to integrate `as.character.mime(body, newline = "\n")` into the script below to be able to place spaces in-between lines, but I couldn't find documentation on this. Any thoughts?

```
library(gmailr)

my_dat <- read_csv("addresses.csv")
email_sender <- 'myemail@gmail.com'
body <- "hello %s,
\n
blah
\n
blah
\n
blah
"

edat <- my_dat %>%
mutate(
    To = sprintf('%s <%s>', lastname, email),
    From = email_sender,
    Subject = sprintf('Your article "%s"', title),
    body = sprintf(body, lastname)) %>%
  select(To, Bcc, From, Subject, body)

emails <- edat %>%
  pmap(mime)

use_secret_file("mykey.json")

safe_send_message <- safely(send_message)
sent_mail <- emails %>%
as.character.map(safe_send_message, newline="\n")

**Comment by jimhester** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
