### ISSUE TITLE
Error in Encoding

### ISSUE THREAD

**Issue by msgoussi** [r-lib/gmailr#85]
created a user defined function using your function send_message
```r
email.message <- function(body){
gmailr::send_message(mime(from = "xxx@gmail.com",
to = "xxx@gmail.com",
subject = "R Progress",
body = "foo"))
}
```
if run in R:
```r
email.message(basename(rstudioapi::getSourceEditorContext()$path))

#> Error in Encoding<-(*tmp*, value = "UTF-8") :
#> a character vector argument expected
```

**Comment by jimhester** [comment]
Sorry I cannot reproduce this error, could you give more details on what is in `body`) and also from this code I think you want to pass the content of the editor, not the path? e.g. `email.message(readLines(rstudioapi::getSourceEditorContext()$path))`
