### ISSUE TITLE
Encoding of retrieved messages

### ISSUE THREAD

**Issue by SimonCoulombe** [r-lib/gmailr#86]
Hi Jim,

I am trying to retrieve messages and run some regexp on the content.  I am retrieving the body of my message as follow:

```
my_message = message(id = "myid", format="full")
body(my_message)
```

The issue I have is that all the French characters are broken and replaced by funky symbols.  Where can I set the encoding to fix this?

Fantastic package, thanks for it.

**Comment by SimonCoulombe** [comment]
I think that wrapping the call to rawToChar in base64url_decode_to_char within a call to iconv would work:
replace:
base64url_decode_to_char <- function(x) { rawToChar(base64decode(gsub("_", "/", gsub("-", "+", x)))) }
)

with:
iconv(rawToChar(base64decode(gsub("_", "/", gsub("-", "+", x$payload$parts[[1]]$body$data)))),from="UTF-8", to="latin1")

**Comment by jimhester** [comment]
@SimonCoulombe if you are still running into this problem could you provide an example email object that shows the issue as an `.Rds`, using `saveRDS(msg, "out.Rds")`.
